### ISSUE TITLE
Run failed due to memory allocation

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/replication-game#13]
```
why@why-MS-7B46 ~/g/s/g/f/replication-game> ./target/release/replication-game \
                                            --prover $REPL_GAME_ID \
                                            --seed $REPL_GAME_SEED \
                                            --timestamp $REPL_GAME_TIMESTAMP \
                                            --size 1048576 \
                                            zigzag > proof.json
generating fake data
running setup
running replicate
Jan 27 11:47:36.368 INFO encoding, layer {}: 0, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:33$ storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 11:49:56.632 INFO returning tree, layer: 0, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs$324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 11:51:14.603 INFO encoding, layer {}: 1, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:33$ storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 11:53:34.762 INFO returning tree, layer: 1, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs$324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 11:54:53.366 INFO encoding, layer {}: 2, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:33$ storage_proofs::layered_drgporep, root: storage-proofs

Jan 27 11:57:13.865 INFO returning tree, layer: 2, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs$324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 11:58:34.048 INFO encoding, layer {}: 3, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:33$ storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:00:54.267 INFO returning tree, layer: 3, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs$324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:02:13.071 INFO encoding, layer {}: 4, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:33$ storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:04:33.173 INFO returning tree, layer: 4, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs$324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:05:53.802 INFO encoding, layer {}: 5, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:33$ storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:08:13.990 INFO returning tree, layer: 5, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs$324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:09:33.903 INFO encoding, layer {}: 6, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:331 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:11:53.822 INFO returning tree, layer: 6, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:13:15.148 INFO encoding, layer {}: 7, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:331 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:15:35.356 INFO returning tree, layer: 7, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:16:53.818 INFO encoding, layer {}: 8, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:331 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:19:13.985 INFO returning tree, layer: 8, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:20:32.873 INFO encoding, layer {}: 9, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:331 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:22:53.108 INFO returning tree, layer: 9, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:26:23.682 INFO returning tree, layer: 10, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:324 storage_proofs::layered_drgporep, root: storage-proofs
Jan 27 12:26:24.299 INFO setting tau/aux, layer: 0, place: /home/why/.cargo/git/checkouts/rust-proofs-e06c0682a2ef6285/51df01e/storage-proofs/src/layered_drgporep.rs:370 storage_proofs::layered_drgporep, root: storage-proofs
memory allocation of 2147483616 bytes failedfish: “./target/release/replication-ga…” terminated by signal SIGABRT (Abort)
```

I have 32 GB of ram, not much else on the system was using it either.

**Comment by yangjian102621** [comment]
failed with 16GB ram

 ./target/release/replication-game \
> --prover $REPL_GAME_ID \
> --seed $REPL_GAME_SEED \
> --timestamp $REPL_GAME_TIMESTAMP \
> --size 1048576 \
> zigzag > proof.json
generating fake data
running setup
running replicate
Mar 05 16:13:14.709 INFO encoding, layer {}: 0, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:401 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:19:06.134 INFO encoding, layer {}: 1, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:401 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:29:25.588 INFO encoding, layer {}: 2, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:401 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:42:55.446 INFO returning tree, layer: 2, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:394 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:42:55.451 INFO returning tree, layer: 0, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:394 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:42:55.451 INFO returning tree, layer: 1, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:394 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:43:43.427 INFO encoding, layer {}: 3, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:401 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:52:59.663 INFO returning tree, layer: 3, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:394 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 16:55:48.125 INFO encoding, layer {}: 4, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:401 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 17:05:20.569 INFO returning tree, layer: 4, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:394 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 17:07:25.692 INFO encoding, layer {}: 5, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:401 storage_proofs::layered_drgporep, root: storage-proofs
Mar 05 17:16:50.912 INFO returning tree, layer: 5, place: /home/yangjian/.cargo/git/checkouts/rust-fil-proofs-4a4e9362af45e2c5/8584f32/storage-proofs/src/layered_drgporep.rs:394 storage_proofs::layered_drgporep, root: storage-proofs
memory allocation of 2147483616 bytes failedAborted

**Comment by dignifiedquire** [comment]
new versions require less memory, still a lot though, but that is not an issue with the game itself
