### ISSUE TITLE
Unable to upload new (larger) proofs

### ISSUE THREAD

**Issue by litianc** [filecoin-project/replication-game#46]
Hi,  i run the following script:
``bin/play blockcasting 10240 drgporep``

it failed

There is the detail message:
``` sh
> curl -s https://replication-game.herokuapp.com/api/seed >seed.json
> target/release/replication-game   --prover 'blockcasting'   --seed '3a56fcd89f53372fc966be07fb1e9517e1062349c010c50d0fd3a74139bab99b523d31d1740339c20af58d7df5d687d78c1e4afc53881c4af76b5ea3b1666347'   --timestamp '1554950587'   --size '10240'   'drgporep' >'proof.json'
generating fake data
running setup
running replicate
sampling proving & verifying
> curl -X POST -H 'Content-Type: application/json' -d '@proof.json' 'https://replication-game.herokuapp.com/api/proof'
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

**Comment by litianc** [comment]
Then I check 'proof.json' file whose size is about 500M
``
$ du -sh proof.json 
498M	proof.json
``

**Comment by litianc** [comment]
After all, I rollback branch to 'jsoares-patch-1'. It works.
`proof.json` file size is 20K

**Comment by dignifiedquire** [comment]
The size is expected to be larger, as the latest version uses a properly scaled amount of challenges. The servers should accept this data though, and not crash :( Investigating

**Comment by dignifiedquire** [comment]
It looks like the problem has may facets :( Now that I fixed the upload limit size, heroku times out, as it only allows requests to take 30s. Looks like this will be more involved to fix.

**Comment by dignifiedquire** [comment]
Heroku doc reference: https://devcenter.heroku.com/articles/request-timeout#uploading-large-files

**Comment by dignifiedquire** [comment]
Okay, I have enabled gzipping the results when uploading them, and reduced the default challenge count to 200, which makes things pass for me again.

**Comment by litianc** [comment]
Cool! Thanks
