### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Iokdo** [filecoin-project/replication-game#52]
Compiling filecoin-proofs v0.1.0 (https://github.com/filecoin-project/rust-fil-proofs?rev=b429279195e08ecf3abd9879a3ef6f3b6fb2e21f#b4292791)
error: failed to run custom build command for `filecoin-proofs v0.1.0 (https://github.com/filecoin-project/rust-fil-proofs?rev=b429279195e08ecf3abd9879a3ef6f3b6fb2e21f#b4292791)`

Caused by:
  process didn't exit successfully: `/Users/sam/Code/rust/replication-game/target/release/build/filecoin-proofs-1b8a2892281660bb/build-script-build` (exit code: 1)
--- stderr
unable to generate bindings: CargoMetadata("/Users/sam/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/b429279/filecoin-proofs/Cargo.toml", Json(Error("EOF while parsing a value", line: 1, column: 0)))

**Comment by dignifiedquire** [comment]
I have just pushed some updates to `master`, can you please try those?
