### ISSUE TITLE
Precompute everything we can before requesting the seed

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/replication-game#54]
For example, the expansion parent indexes (ZigZag case) which don't depend on it and are expensive to compute.

(edit: seems like the base parents depend on a fixed seed so they can be precomputed as well, although Feistel is still by far the most expensive of the two)

**Comment by dignifiedquire** [comment]
I think this is the wrong repo ;)

**Comment by schomatis** [comment]
Haha, fair enough. I meant that I don't want participants wasting time and effort on this optimization that I think we should provide ourselves, I'd rather have them focusing on more interesting software and hardware optimizations that would actually add value to the competition. As it stands this is just a tax we're imposing on anyone trying to competitively participate (because this pre-computation makes a considerable difference and they can't ignore it).

But you're right that this should be discussed in `rust-fil-proofs` (if we indeed want to provide an option of the sort), I submitted here because it seemed relevant to the competition itself.
